### ISSUE TITLE
Error when reading TraCICoord from TraCIBuffer

### ISSUE THREAD

**Issue by dbuse** [sommer/veins#179]
https://github.com/sommer/veins/blob/78447d0c323baa7cc35e29ac88c71fb768432607/src/veins/modules/mobility/traci/TraCIBuffer.cc#L122-L133
This method should read a `TraCICoord` from a `TraCIBuffer`, similar to how other primitive types are read. However, it first reads a `uint8_t` assuming that this is the TraCI Type-Code for a `POSITION_2D`.

The problem is that no other type of `TraCIBuffer::read` does this! They all assume the typecode-byte has already been read. This means that if `TraCIBuffer::read<TraCICoord>` reads one byte further in the buffer than its user would assume, which could result in broken buffers. Also, the contents of the returned `TraCICoord` could be corrupted.

Note that `TraCIBuffer::read<TraCICoord>` is not currently used anywhere in Veins' codebase. This explains why this error has gone unnoticed for years.

**Comment by mightyCelu** [comment]
This issue seems to also apply to `TraCIBuffer::write(TraCICoord)`, which writes the type code, while the outher `TracIBuffer::write` overloads don't. I did not check whether this method is acutally used in the codebase however.

**Comment by dbuse** [comment]
Good point, @mightyCelu ! `TraCIBuffer::write(TraCICoord)` is actually used a couple of times in `TraCICommandInterface` (`getLonLat`, `getRoadMapPos`, `getDistance`, and `addPoi`, according to sourcetrail). And it indeed is used differently than other types there. I'll add a commit to normalize this as well.
