### ISSUE TITLE
Missing Enter_Method_Silent

### ISSUE THREAD

**Issue by michele-segata** [sommer/veins#184]
I am pointing out a simple issue due to a mistake of mine. In a recent PR I've added the `setMacAddress()` method to `BaseMacLayer` (83e7d8761d). As this method might be called directly by other modules, there should be a call to `Enter_Method_Silent()` at the beginning of the method, right? If you confirm this is the case, I can fix this with a simple commit referring to this issue.

**Comment by sommer** [comment]
Sounds like a good idea!
