### ISSUE TITLE
How can I modify veins source code in which RSU send wsa to a specific node?

### ISSUE THREAD

**Issue by zawarafzl** [sommer/veins#186]
I have a scenario where every RSU will broadcast WSA (Wave Service Advertisement) to a specific vehicles in the range and the vehicle has to store it. I am new in VEINS Can anyone please help me how to make changes in TraCIDemoRSU11p.cc thanks in advance

**Comment by sommer** [comment]
We're using the issue tracker to track problems in Veins. You're unlikely to get good support here if you have problems using Veins. For programming questions, my recommendation is [StackOverflow](https://stackoverflow.com/questions/tagged/veins), for general questions my recommendation is the OMNeT++ users' mailing list.

**Comment by zawarafzl** [comment]
https://stackoverflow.com/questions/61255482/how-can-i-modify-veins-source-code-in-which-rsu-send-wsa-to-a-specific-node 
christoph sommer SIR i had asked a question on Stack-overflow would you like to answer my ploblem over there please
