### ISSUE TITLE
TraCIMobility records last position instead of current position

### ISSUE THREAD

**Issue by FlorianNolte** [sommer/veins#190]
In TraCIMobility, the recorded position in lines 195 and 196 (see https://github.com/sommer/veins/blob/veins-5.0/src/veins/modules/mobility/traci/TraCIMobility.cc#L195) is the position before the position change in a timestep. 
Thus, it does not match the other recorded values of a timestep, but rather is one timestep behind. This also leads to the fact that the position recorded in timestep 0 is always the same as the position recorded in timestep 1 regardless of how long one timestep actually is. 

I would propose to just record nextPos as it is calculated in https://github.com/sommer/veins/blob/veins-5.0/src/veins/modules/mobility/traci/TraCIMobility.cc#L198 because this is the actual position received by TraCI. And I would name it other than nextPos as it might me confusing.

**Comment by sommer** [comment]
Agreed! Committed as https://github.com/sommer/veins/commit/c6e7ac7c04d0767fb31376d6f7f106ac85c1e4bb
