### ISSUE TITLE
Using inetmanet with veins

### ISSUE THREAD

**Issue by tamarbuterman** [sommer/veins#192]
I want to use veins (latest version) and inetmanet (version 4.x) using veins_inet and I have a compilation error 
where veins_inet call inetmant functions af some classes
<img width="601" alt="pic" src="https://user-images.githubusercontent.com/57418567/92152887-1b2b0f80-ee2c-11ea-8c14-1f844b86e487.PNG">
 (the function does not return what it is expected to return).
Do you know of a way to solve this problem?
Thank you!

**Comment by chaotictoejam** [comment]
@tamarbuterman The PR I have open resolves this: https://github.com/sommer/veins/pull/191

**Comment by tamarbuterman** [comment]
Thanks a lot!
