### ISSUE TITLE
veins_inet

### ISSUE THREAD

**Issue by axida-stack** [sommer/veins#193]
I want to access the node speed in AODVRouting.cc file which from INET framework. 
I have included the #include "veins_inet/VeinsInetMobility.h" in AODVRouting.cc. 
I added a line of codes, like VeinsInetMobility* inetmm = dynamic_cast<VeinsInetMobility*>(submod);
I got 'VeinsInetMobility' was not declared in this scope error. how to solve this kind problems?
Thank you in advance!

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
