### ISSUE TITLE
The variable “curSpeed” in handlePositionUpdate(cObject* obj) is equal to (-0,0,0)

### ISSUE THREAD

**Issue by shengun567** [sommer/veins#198]
When I run the examples in veins5.0, I find the value of curSpeed is equal to (-0,0,0). Why?
```
void DemoBaseApplLayer::handlePositionUpdate(cObject* obj)
{
    ChannelMobilityPtrType const mobility = check_and_cast<ChannelMobilityPtrType>(obj);
    curPosition = mobility->getPositionAt(simTime());
    curSpeed = mobility->getCurrentSpeed();
    EV<<"DemoBaseApplLayer::handlePositionUpdate curSpeed="<<curSpeed<<endl;
}
```

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
