### ISSUE TITLE
how to resolve the warning: #warning Please include winsock2.h before windows.h

### ISSUE THREAD

**Issue by mateen-malik** [sommer/veins#200]
hi,

i got the following warning while building veins-5.1 in OMNet ++ version 5.6.2 ,

#warning Please include winsock2.h before windows.h

Wondering how to fix this?

Thanks in advance,

Best regards,
/MM

**Comment by sommer** [comment]
Warning resolved in 0b016e789b8d4579f34db6cbb27fb3a1d3e0640f ("visualizer: minimize header dependencies, warnings on Windows"). You might also be interested in a7754706802dca688b3ae753ba8b4a73f87d64d8 ("traci: minimize warnings on Windows"), which further reduces the amount of warnings you will see on Windows. Depending on your OMNeT++ version and whether you intend to link external projects against Veins 5.1, 01c22e650bbd52e7081c5e07a342e491c5b5574b ("windows: add INET 4.2.1 workarounds for linking with clang") might also be of interest to you.
