### ISSUE TITLE
Question: how to enable forward & backward antenna mode

### ISSUE THREAD

**Issue by pengyuan-zhou** [sommer/veins#201]
Hi,

Sorry for posting this way, but due to lack of knowledge in antenna, I've got to propose a question as an issue here:
how to add backward antenna, like a reversed version of "patch" mode, on to current "patch" configuration in [antenna.xml](https://github.com/sommer/veins/blob/b8637c811adaef95cd51f3b2e3dc45af0e08e463/examples/veins/antenna.xml) ?

Currenly my understanding of the sample values is, the 72 values in patch mode refer to a circle, each value refer to a pi/36 theta. However when plotting the values in polar following that understanding, the figure looks quite different from the orginal paper's figure where the samples came from.

Here's the plot
<img width="237" alt="Screenshot 2021-01-03 at 1 52 04" src="https://user-images.githubusercontent.com/20013315/103463464-7da70480-4d67-11eb-9c8c-7a92f22b04c1.png">

Here is the original one
<img width="237" alt="Screenshot 2021-01-03 at 1 55 07" src="https://user-images.githubusercontent.com/20013315/103463472-944d5b80-4d67-11eb-93bb-f599a7a239ab.png">

Could you elaborate how the values map to x/y axis?

Thank you.
BR.
PZ

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
