### ISSUE TITLE
cannot find VehicleObstacleControl module -- in module (veins::PhyLayer80211p)

### ISSUE THREAD

**Issue by pengyuan-zhou** [sommer/veins#203]
Hi, 

I met this error when testing the vehicle obstacle model in veins-5.0. 
```
initializeVehicleObstacleShadowing(): cannot find 
VehicleObstacleControl module -- in module (veins::PhyLayer80211p) 
RSUExampleScenario.rsu[0].nic.phy80211p (id=11), 
during network initializatio
```
Yet I do find VehicleObstacleControl written in PyLayer80211p.cc as follows
```
unique_ptr<AnalogueModel> PhyLayer80211p::initializeVehicleObstacleShadowing(ParameterMap& params)
{

    // init with default value
    bool useTorus = world->useTorus();
    const Coord& playgroundSize = *(world->getPgs());

    ParameterMap::iterator it;

    VehicleObstacleControl* vehicleObstacleControlP = VehicleObstacleControlAccess().getIfExists();
    if (!vehicleObstacleControlP) throw cRuntimeError("initializeVehicleObstacleShadowing(): cannot find VehicleObstacleControl module");
    return make_unique<VehicleObstacleShadowing>(this, *vehicleObstacleControlP, useTorus, playgroundSize);
}
```

Appreciate if you could give me any guidance.
Thank you :)
BR.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
