### ISSUE TITLE
Streaming input/output  on viens simulation using omnet++

### ISSUE THREAD

**Issue by Anasboulbali** [sommer/veins#204]
How to make an RSU able to read 'BSM' data from a 'JSON' or 'XML' file and then send them to vehicles and also if it is possible to directly connect OMNET ++ to another server (our server) so that once OMNET ++ is connected, the RSU receives the 'BSM' data stream and sends it to vehicles in real time.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
