### ISSUE TITLE
Connection to TraCI server lost. Check your server's log

### ISSUE THREAD

**Issue by mateen-malik** [sommer/veins#206]
Hi,

I need your help regaring the follwing issue i am facing,

I have installed SUMO, Omnet and Veins in Ubuntu. I start the port listening and when i run the example in veins the following error i got. 

**A runtime error occurred:

Connection to TraCI server lost. Check your server's log. Error message: 104: Connection reset by peer -- in module (veins::TraCIScenarioManagerLaunchd) RSUExampleScenario.manager (id=6), at t=0s, event #1

Launch a debugger with the following command?

nemiver --attach=2774 &**

![image](https://user-images.githubusercontent.com/74792496/110545790-e9be3400-812d-11eb-9854-5f94a296a927.png)
![image](https://user-images.githubusercontent.com/74792496/110545868-0490a880-812e-11eb-8550-120e59d6cc2d.png)

Can you please help resolving this issue?

**Versions:** 
Ubuntu 20.04.2 LTS
OMNeT ++ 5.6.2
SUMO 1.8.0
Veins 5.1

Thanks in advance,

Best regards,
/Mateen

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
