### ISSUE TITLE
Error: Storage::readChar(): invalid position

### ISSUE THREAD

**Issue by mateen-malik** [sommer/veins#207]
Hi,

I have one more issue that is when i run the example from Veins in Omnet, The simulations start and quickly after that gives the following error,

---------------------------------------------------------------------------------------
Loading configuration ... done.
***Starting server on port 45595 ***
Loading net-file from 'erlangen.net.xml' ... done (218ms).
Loading additional-files from 'erlangen.poly.xml' ... done (5ms).
Loading done.
Simulation started with time: 0.00
**Error: Storage::readChar(): invalid position
Quitting (on error).**

Below is the screenshot of my terminal, 
![image](https://user-images.githubusercontent.com/74792496/110553068-b339e680-8138-11eb-885a-7bb4f5790d23.png)

I also get this message,

![image](https://user-images.githubusercontent.com/74792496/110553216-f1cfa100-8138-11eb-996e-9e53b09f2af5.png)

When i force quit i got the following,

![image](https://user-images.githubusercontent.com/74792496/110553414-38bd9680-8139-11eb-9840-20b9054c6f77.png)

Can you please help identifying what is the issue and what can i do to resolve it?

Thanks alot in advance,

Best regards,
/MM

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/

**Comment by I-ikshvaku** [comment]
I was doing the same thing and find this problem, also the documentation of veins isn't helpful, kindly help me asap

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/

**Comment by Thilaga22** [comment]
I am also facing the same situation. Anyone found out the solution?
Please help.

**Comment by Thilaga22** [comment]
> Hi,
> 
> I have one more issue that is when i run the example from Veins in Omnet, The simulations start and quickly after that gives the following error,
> 
> Loading configuration ... done.
> ***Starting server on port 45595 ***
> Loading net-file from 'erlangen.net.xml' ... done (218ms).
> Loading additional-files from 'erlangen.poly.xml' ... done (5ms).
> Loading done.
> Simulation started with time: 0.00
> **Error: Storage::readChar(): invalid position Quitting (on error).**
> 
> Below is the screenshot of my terminal,
> ![image](https://user-images.githubusercontent.com/74792496/110553068-b339e680-8138-11eb-885a-7bb4f5790d23.png)
> 
> I also get this message,
> 
> ![image](https://user-images.githubusercontent.com/74792496/110553216-f1cfa100-8138-11eb-996e-9e53b09f2af5.png)
> 
> When i force quit i got the following,
> 
> ![image](https://user-images.githubusercontent.com/74792496/110553414-38bd9680-8139-11eb-9840-20b9054c6f77.png)
> 
> Can you please help identifying what is the issue and what can i do to resolve it?
> 
> Thanks alot in advance,
> 
> Best regards,
> /MM

I am facing the same problem.
Have you found the solution to proceed further?

**Comment by sommer** [comment]
For ease of reference, these are two example questions on StackOverflow that discuss common oversights leading to the mentioned message:

https://stackoverflow.com/q/66566806/4707703

https://stackoverflow.com/q/67822142/4707703

**Comment by Thilaga22** [comment]
> For ease of reference, these are two example questions on StackOverflow that discuss common oversights leading to the mentioned message:
> 
> https://stackoverflow.com/q/66566806/4707703
> 
> https://stackoverflow.com/q/67822142/4707703

Dear Sommer,
I truly appreciate your response.
I was using Sumo 1.9.1 version,
Now I upgraded to Sumo 1.9.2 version and now its working fine. 
Thanks a lot.

Thilaga.
