### ISSUE TITLE
Connection to TraCI server lost while using veins

### ISSUE THREAD

**Issue by divakar5** [sommer/veins#208]
I'm getting the below issue

divakar@divakar:~/veins-5.1/veins-veins-5.1$ ./sumo-launchd.py -vv -c sumo
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirecting.
Logging to /tmp/sumo-launchd.log
Listening on port 9999
Connection from 127.0.0.1 on port 44898
Handling connection from 127.0.0.1 on port 44898
Got TraCI message of length 2
Got TraCI command of length 1
Got TraCI command 0x0
Got CMD_GETVERSION
Got TraCI message of length 304
Got TraCI command of length 299
Got TraCI command 0x75
Got CMD_FILE_SEND for "b'sumo-launchd.launch.xml'"
Got CMD_FILE_SEND with data "b'\n \n \n \n \n \n \n\n'"
Creating temporary directory...
Temporary dir is /tmp/sumo-launchd-tmp-kxqifxm5
Base dir is /home/divakar/veins-5.1/veins-veins-5.1/examples/veins/
Seed is 0
Finding free port number...
Claiming lock on port
...found port 40991
Starting SUMO (sumo -c erlangen.sumo.cfg) on port 40991, seed 0
Connecting to SUMO (sumo -c erlangen.sumo.cfg) on port 40991 (try 1)
Error ([Errno 111] Connection refused)
Connecting to SUMO (sumo -c erlangen.sumo.cfg) on port 40991 (try 2)
Releasing lock on port
Starting proxy mode
Done with proxy mode
Done with proxy mode, killing SUMO
Done running SUMO
Cleaning up
Result: "

1
1616690356
1616690357
Exited with error code 1

"
Closing connection from 127.0.0.1 on port 44898
^CKeyboard interrupt.
Shutting down.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirection done.
WARNING: the sumo-launchd.py script is deprecated in favor of bin/veins_launchd. Redirection done.

I tried adding log value="log.txt" and verbose value="true" in erlangen.sumo.cfg (in veins example) after that i triggered simulation i got same error and Omnetpp console displayed the below error.

terminate called after throwing an instance of 'omnetpp::cRuntimeError'
what(): Connection to TraCI server lost. Check your server's log. Error message: 32: Broken pipe

Please guide me, I'm new to this domain.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
