### ISSUE TITLE
Possibility to access for Veins parameters from Python

### ISSUE THREAD

**Issue by mehdi-maleki** [sommer/veins#210]
Hello!

I'm looking for a way to run Omnet/Veins from Python, the purpose is:
1. To be able to run the simulation for many times automatically.
2. Access to the different parameters in communication layers in Veins (retrieve and if need change that parameter's value).

I was wondering if it is possible to write some Python-scripts to conncet to the Omnet/Veins via for example TCP/IP protocol?!

Any suggestions would be helpful.
Thanks in advance!

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/

**Comment by mehdi-maleki** [comment]
Thanks for the feedback!
Sure, I'll check that.

**Comment by dbuse** [comment]
You could also take a look into Veins-Gym, for which we also had to to the two things you mentioned: https://github.com/tkn-tub/veins-gym
