### ISSUE TITLE
inet_veins problem

### ISSUE THREAD

**Issue by shriyaBhat1** [sommer/veins#215]
Creating shared library: ../out/clang-release/src/libVANET.dll
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x7f8): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::finish()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0xc80): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::init_traci()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x12e8): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::~TraCIScenarioManagerLaunchd()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x12f0): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::~TraCIScenarioManagerLaunchd()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x13d8): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::initialize(int)'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x13f0): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::finish()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.rdata+0x1878): undefined reference to `virtual thunk to veins::TraCIScenarioManagerLaunchd::init_traci()'
../out/clang-release/src/veins_inet/VeinsInetManager.o:(.text[_ZN5veins22SignalCallbackListenerIPN7omnetpp7cObjectEEC2ESt8functionIFvNS_13SignalPayloadIS3_EEEEPNS1_7cModuleEi]+0x25): undefined reference to `__imp__ZTVN5veins22SignalCallbackListenerIPN7omnetpp7cObjectEEE'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:112: ../out/clang-release/src/libVANET.dll] Error 1
make[1]: Leaving directory '/c/Users/Shriya/omnetpp-5.6.2/samples/project/VANET/src'
make: *** [Makefile:2: all] Error 2
"make MODE=release all" terminated with exit code 2. Build might be incomplete.

**Comment by sommer** [comment]
Incomplete bug report. Unable to reproduce.
