### ISSUE TITLE
i want run veins without "Obstacle Shadowing"

### ISSUE THREAD

**Issue by GyeongtaeGim** [sommer/veins#217]
I want to simulate more than 100 vehicles. but, it's so slow. 
therefore, i try to disable "Obstacle Shadowing" or disable "analogueModel".

Is there a way?(like... option) or i should be customizing and develop code?

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
