### ISSUE TITLE
Veins_inet Subproject

### ISSUE THREAD

**Issue by Thilaga22** [sommer/veins#218]
I am using Veins current version , OMNEST 5.6.2 and inet-4.2.5-e0c1741924 version, windows 10.
I am getting the errors as attached in the image.
Any help on this?

![image](https://user-images.githubusercontent.com/85918822/129298142-2e865bef-e39f-429c-820c-b958102475bb.png)
![image](https://user-images.githubusercontent.com/85918822/129298359-ebd98c6c-c407-460c-9182-b0107fed9bea.png)

**Comment by sommer** [comment]
Could you please comment on https://github.com/sommer/veins/issues/212 ?

**Comment by sommer** [comment]
Likely fixed by #212, closing
