### ISSUE TITLE
Errors while building Veins Inet Subproject

### ISSUE THREAD

**Issue by Gulabi-star** [sommer/veins#222]
Hello,
Good greetings, 

I am encountering errors while executing the build project command for Veins Inet subproject. A screenshot of the error message has been attached.   
I have followed the following steps,
1. Installed Oracle Virtual Box on my windows 10 system
2. Installed Ubuntu 20.04.3 LTS from [link](https://ubuntu.com/download/desktop)
3. Installed OMNeT++ 6.0  pre 11 from [link](https://github.com/omnetpp/omnetpp/releases/tag/omnetpp-6.0pre11). I have followed all the steps mentioned in the OMNeT++ installation guide. Also, followed the comments mentioned on [link](https://githubmemory.com/repo/Unipisa/Simu5G/issues/6), and edited the line PREFER_CLANG = no in the "configure.user" file present in the omnetpp-6.0 pre11 directory. It is running successfully.
4. Imported project, and did build project for INET 4.3.2. Downloaded from [link](https://github.com/inet-framework/inet/releases/tag/v4.3.2). It is running without any errors. However, a message  "features.h file is missing"  popped up when I initiated the build project. I ignored it and proceeded with the build project. The screenshot of this message is attached.  
5. Installed Veins from [link](https://github.com/sommer/veins). While importing the files, I extracted/copied  the Veins Inet subproject into my workspace. The "gcc-debug build" was selected as the build configuration when I did the build project for Veins Inet. This is where I encountered the errors (image is attached). 

Please help me figure out where I am going wrong in my steps followed. Please guide me to build the veins inet successfully in my system. 
Hoping to hear from you soon, 

Regards, 
Thanking you, 
Gulabi Mandal 
![Inet popup(1)](https://user-images.githubusercontent.com/85755755/133931641-f4cf9f93-d88c-4643-a2db-909d1d307f81.png)
![Veins_inet error](https://user-images.githubusercontent.com/85755755/133931642-3cf289ea-7f67-40a6-a717-428b24f8d81f.png)

**Comment by Gulabi-star** [comment]
Hello, 
Good greetings,
We followed up with the comment mentioned on [link](https://githubmemory.com/repo/Unipisa/Simu5G/issues/6), and edited the line PREFER_CLANG = no in the "configure.user" file present in the omnetpp-6.0 pre11 directory. 
For the [INET 4.3.2](https://github.com/inet-framework/inet/releases/tag/v4.3.2), we did "import project" into the workspace, and then "build project". A message "features.h file is missing" popped up when we initiated the build project. Although the build project runs without any errors, this step causes a ripple effect in generating a series of errors in Veins_Inet, and Simu5G "build project" execution.
We found that both the .zip file and .tgz file of INET 4.3.2 do not contain the "features.h" file (images are attached for ready reference). This could be the reason for facing such errors (as mentioned in the previous email above) in the consecutive steps.  
As per our request, a colleague has shared the INET 4.3.2 zip file containing the "features.h" file (Image is attached). In the follow-up, the OMNeT++ example simulation, and the Simu5G is running successfully. 

Thank you, 
Regards, 
Gulabi Mandal

![ZipFile_Features_h_missing](https://user-images.githubusercontent.com/85755755/135738323-bfec6436-9b52-49d1-83d2-c56c796f6b1c.png)
![ZipFile_with_Features_h_Present](https://user-images.githubusercontent.com/85755755/135738324-0c8d723a-a92f-4d82-87af-c118998c67cf.png)
![tgzfile_Features_h_missing](https://user-images.githubusercontent.com/85755755/135738325-27ff82a9-db80-409e-9855-008efb7f7523.png)

**Comment by sommer** [comment]
Thank you for sharing both the problem and its solution! Veins 5.2 should now also build and link on Windows with the clang toolchain of OMNeT++ 6.0pre14.
