### ISSUE TITLE
I was able to overtake using the oncoming lane in sumo, but it is not reflected in omnet++.

### ISSUE THREAD

**Issue by RYO-teni015** [sommer/veins#224]
Hi.

I'm trying to overtake a car using the oncoming lane when the front is blocked.

In "sumo", when I do a "netconvert", I can overtake the car with an option, but when I reflect the car to "omnet++" through "veins", the car does not change its movement, it just follows the car in front.

What can I do to solve this problem?

I am sorry, but I would appreciate it if you could help me.

The tools I am using are sumo (1.8.0) veins (5.1) omnet++ (5.6.2)

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
