### ISSUE TITLE
recording RSSI and BSM sender address in Veins 5.1 [help wanted]

### ISSUE THREAD

**Issue by gsohan** [sommer/veins#225]
Hi,

I am running a simulation in which vehicles exchange BSM messages with each other. I want to measure RSSI and BSM sender address using Veins 5.1; as Veins 5.1 has some new updates especially BaseFrame1609_4 file. Previous I was able to record RSSI, senderAddress information using WaveShortMessage which has been replaced by BaseFrame1609_4 in Veins 5. 

In addition, when I do sendDown(BSM) in my application; I see BSM message is being sent but not received on receiver side. I am using the similar code as DemoBasApplLayer. What might be the issue for not being able to receive the BSM message (i verified that message is being sent but not received on receiver side)

Your help and suggestions will be highly appreciated.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
