### ISSUE TITLE
DielectricObstacleLoss does not work as expect in the veins_inet example

### ISSUE THREAD

**Issue by YichaoXu** [sommer/veins#227]
Hi Sommer, 

I recently ran the example in the subproject [veins_inet](https://github.com/sommer/veins/tree/master/subprojects/veins_inet/examples/veins_inet). I noticed that the IdealObstacleLoss worked well in there. However, when I try to use the "DielectricObstacleLoss" and change the obstacle to vacuum. The vehicle did not work as expected. 

Specifically, I changed the two files: 
> In [veins_inet/Scenario.ned](https://github.com/sommer/veins/blob/master/subprojects/veins_inet/examples/veins_inet/Scenario.ned), I changed the obstacleLoss from "IdealObstacleLoss" to "DielectricObstacleLoss"
```c++
- 49:    *.radioMedium.obstacleLoss.typename = "IdealObstacleLoss"
+ 49:    *.radioMedium.obstacleLoss.typename = "DielectricObstacleLoss"
```
> In [veins_inet/obstacles.xml](https://github.com/sommer/veins/blob/master/subprojects/veins_inet/examples/veins_inet/obstacles.xml), I changed the material from "copper" to "air"

 ```xml
- 35:    <object ... material="copper" ... />
+ 35:    <object ... material="air" ... />
```

As the image below show, I expect that the node[2] will receive the message from the node[0], but it did not. 

<figure>
<img style="width:50%; padding-left:25%; " src="https://user-images.githubusercontent.com/35974430/151655109-a46f3625-209d-4427-8cc9-751910ffaab6.png"/>
</figure>

The event output proves this, where I did not notice any packet from node[2] to node[0] directly.
```
#231	20	node[0] --> node[1]	accident	10.0.0.37:9001	224.0.0.1:9001	UDP	DATA	175 B	(UNKNOWN) VeinsInetSampleMessage, length = 100 B | 9001->9001, payload:100 B | IPv4 id:0 ttl:1 payload:udp 108 B | etherType: 2048 | WLAN  | (IEEE 802.11 Phy) inet::physicallayer::Ieee80211OfdmPhyHeader, length = 5 B | len=171B duration=152us (encapsulates 171B) src=Scenario.node[0].wlan[0].radio (id=57)  dest=Scenario.node[1].wlan[0].radio (id=119)
#231	20	node[0] --> node[2]	accident	10.0.0.37:9001	224.0.0.1:9001	UDP	DATA	175 B	(UNKNOWN) VeinsInetSampleMessage, length = 100 B | 9001->9001, payload:100 B | IPv4 id:0 ttl:1 payload:udp 108 B | etherType: 2048 | WLAN  | (IEEE 802.11 Phy) inet::physicallayer::Ieee80211OfdmPhyHeader, length = 5 B | len=171B duration=152us (encapsulates 171B) src=Scenario.node[0].wlan[0].radio (id=57)  dest=Scenario.node[2].wlan[0].radio (id=181)
#254	20.000236182948	node[1] --> node[0]	relay	10.0.0.99:9001	224.0.0.1:9001	UDP	DATA	175 B	(UNKNOWN) VeinsInetSampleMessage, length = 100 B | 9001->9001, payload:100 B | IPv4 id:0 ttl:1 payload:udp 108 B | etherType: 2048 | WLAN  | (IEEE 802.11 Phy) inet::physicallayer::Ieee80211OfdmPhyHeader, length = 5 B | len=171B duration=152us (encapsulates 171B) src=Scenario.node[1].wlan[0].radio (id=119)  dest=Scenario.node[0].wlan[0].radio (id=57)
#254	20.000236182948	node[1] --> node[2]	relay	10.0.0.99:9001	224.0.0.1:9001	UDP	DATA	175 B	(UNKNOWN) VeinsInetSampleMessage, length = 100 B | 9001->9001, payload:100 B | IPv4 id:0 ttl:1 payload:udp 108 B | etherType: 2048 | WLAN  | (IEEE 802.11 Phy) inet::physicallayer::Ieee80211OfdmPhyHeader, length = 5 B | len=171B duration=152us (encapsulates 171B) src=Scenario.node[1].wlan[0].radio (id=119)  dest=Scenario.node[2].wlan[0].radio (id=181)

```

I was wondering whether it is a bug in the veins_inet or inet? or I misunderstand the something in there? 

Best, 
Yichao

**Comment by sommer** [comment]
The `veins_inet` example is using `radioMedium.obstacleLoss.typename = "IdealObstacleLoss"`, that is, independent of the computed loss for an obstacle, it always absorbs radio waves perfectly (see https://github.com/inet-framework/inet/blob/v4.3.7/src/inet/physicallayer/wireless/common/obstacleloss/IdealObstacleLoss.cc#L71). To use a different loss model, you would need to switch to something like `DielectricObstacleLoss`. Then, if you would like your obstacle to cause only little power loss, configure it something like this:
```
<material id="mymaterial" relativePermittivity="1e8" relativePermeability="1e-8" resistivity="1"/>
<object position="min 40 50 0" orientation="0 0 0" shape="cuboid 70 60 20" material="mymaterial" fill-color="235 128 32" opacity="0.8" />
```
