### ISSUE TITLE
veins with fog computing

### ISSUE THREAD

**Issue by muhammedhani** [sommer/veins#228]
Can RSU be used as a fog node in a veins example, and how can this be done? Also, can this be done without configuring the fog nodes myself?

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
