### ISSUE TITLE
The veins_inet example does not run

### ISSUE THREAD

**Issue by Krystal522** [sommer/veins#229]
Hi Sommer,

I recently ran the example in the subproject [veins_inet](https://github.com/sommer/veins/tree/master/subprojects/veins_inet/examples/veins_inet). but the example can't work.

Specifically, the  error is :

make: *** [Makefile:2: all] Error 2
make[1]: *** [Makefile:128: ../out/gcc-release/src/VANETTurorials.exe] Error 1

What is the reason for this?

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
