### ISSUE TITLE
Veins : BaseMaclayer coding error

### ISSUE THREAD

**Issue by CSSIA** [sommer/veins#23]
Hi all, 

I'm newbies on this Omnet simulator. Would like to know more about this simulator as well. When building the Veins in Omnet simulator found out this error message at the screenshot below on Line 74.
![veins coding error](https://cloud.githubusercontent.com/assets/25496675/22547544/12bd9d2a-e97d-11e6-87df-6881c121e528.png)

Attached is the zip file from Veins original folder downloaded from Veins website. 

[BaseMacLayer.zip](https://github.com/sommer/veins/files/747561/BaseMacLayer.zip)

Appreciate if someone can help me on this. 

Thanks in advance.

Regards,

**Comment by namnatulco** [comment]
The file you uploaded is identical to the one in the repository. Can you compile the code on master, or did you make any changes?

It'd probably be more helpful if you posted the complete compile error and which compiler you're using.

**Comment by CSSIA** [comment]
Hi, 

I didn't do any changes to the code. When building the Veins on Omnet it gives this type of error. I'm using Code Writer from Window 10 to check the code, not using any compiler on it yet.

Hope you can help me on it. 

Thanks.

**Comment by namnatulco** [comment]
Your screenshot contains half of a compile error. I'm not sure how you obtained a compile error without using a compiler.

**Comment by CSSIA** [comment]
Hi, 

Just now I using Dev-C++ compiler and getting this error as below.

![image](https://cloud.githubusercontent.com/assets/25496675/22548323/e058171c-e980-11e6-9e14-a13b5555ec13.png)

Thanks.

**Comment by CSSIA** [comment]
Attached is the message while building Veins in Omnet. 
[Error message Veins in Omnet.zip](https://github.com/sommer/veins/files/747622/Error.message.Veins.in.Omnet.zip)
Hope this helpful to give you to help me on this. 

Thanks.

**Comment by sommer** [comment]
You have posted your question to the Veins issue tracker. This is for reporting errors in Veins. It is not a public support forum. Kindly refer to the FAQ at http://veins.car2x.org/documentation/faq/

**Comment by CSSIA** [comment]
Post on this issue for Veins because there is an error on it  for file BaseMacLayer.cc . I'm reporting the error at here. So that you guys notice about it. Otherwise, where I can get help for the error occurred on veins file. Please understand the situation first before post it. Apologise if I quite rude about it.

**Comment by ryuuzaki42** [comment]
Use the [stackoverflow](https://stackoverflow.com/) with the tag `veins` and use more details as possible about the error, (https://stackoverflow.com/questions/tagged/veins).

**Comment by ryuuzaki42** [comment]
Use the [stackoverflow](https://stackoverflow.com/) with the tag `veins` and with more details as possible about the error, (https://stackoverflow.com/questions/tagged/veins).
