### ISSUE TITLE
How to run SUMO python traci scrip on OMNEST using viens

### ISSUE THREAD

**Issue by Thilaga22** [sommer/veins#230]
Hi, 

I am working on SUMO VEINS and OMNEST.
To run sumo files on OMNEST, the input of sumo files (.xml) are inputted in veins_launchd, which in turn finds an unused port, starts sumo and bridges the connection between sumo and OMNEST.

I want to control the vehicle's behavior (Speed change) on real time (during the simulation). 
For this purpose, I have written a Traci script in python language, which calls sumo config file and controls vehicle speed on real time 

My issue is, 
I do not know how to make this Traci script (python) to run on OMNEST via veins.
Where should I give this python file as input so that I can visualize the output in OMNEST.

Based on some research, I figured out 2 methods. 
1. TraCIScenarioManager module.
2. Veins_Python

Method1:  I understood by using  TraCIScenarioManager module, OMNEST can directly connect to the running sumo. 
But I don't know where should I make the necessary changes inside veins module to use TraCIScenarioManager instead TraCIScenarioManagerLaunchd

Method2: Regarding veins_python, I downloaded the source file from github and did the configuration steps as mentioned.
I used windows10 and 
Versions: Veins5.0, OMNeT++ 5.5.1 and Python3.6 
But I got the below error while configuring Veins_Python. 

![image](https://user-images.githubusercontent.com/85918822/158145765-23694a3e-b843-4461-98d7-5c400119b25e.png)

I also tried with the recent versions of software on windows 10 
Versions: Veins5.2, OMNEST-5.6.2 and Python3.10 
Still I get the same error. 

I have enclosed my Sumo Traci script (txt) for your reference.
[sumo_run_variablespeed.txt](https://github.com/sommer/veins/files/8243572/sumo_run_variablespeed.txt)

It would be really helpful if you could suggest me the procedure or tutorial for executing my Sumo's traci script on OMNEST. 

Best Regards,
Thilaga.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
