### ISSUE TITLE
Veins Build Error

### ISSUE THREAD

**Issue by monologconnor** [sommer/veins#234]
Hi, there.

I'm currently using `OmNet++ 16.0` with the `INET 4.3.9` and the `latest Simu5G` from their master branch.
I have tried both `Veins 5.2` and the lastest Veins source code from master branch, but all of them report error while building.

The error message is like below:

```
D:\Documents\Omnetpp\omnetpp-6.0\tools\win32.x86_64\mingw64\bin/llvm-ar.exe: error: unable to load '../out/gcc-debug/src/libveins_dbg.dll.a': No such file or directory
make[1]: *** [Makefile:224: ../out/gcc-debug/src/libveins_dbg.dll] Error 1
make[1]: Leaving directory '/d/Documents/Simu5G/veins-veins-5.2/src'
make: *** [Makefile:36: all] Error 2
"make MODE=debug -j8 all" terminated with exit code 2. Build might be incomplete.
```

And prior to this, the console also shows lots of `lld-link error`, like:
```
lld-link: error: undefined symbol: __declspec(dllimport) getsockname
>>> referenced by veins/modules/mobility/traci/TraCIScenarioManagerForker.cc:146
>>>               ../out/gcc-debug/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.o:(veins::TraCIScenarioManagerForker::getPortNumber() const)
```

I have not tried different versions of OmNet and INET, since the building of OmNet takes such a long time, so I'm not sure if that's a compatibility issue. I'm currently using Windows 11 and I'm considering the issue of link-library option from cmake, since similar issue happens to Simu5G in my case.

Thanks for your help

**Comment by sommer** [comment]
Building on Windows is covered on the page at http://veins.car2x.org/download/#compatibility
