### ISSUE TITLE
Changing communicationRange in VeinsInetCar

### ISSUE THREAD

**Issue by ssooffiiaannee** [sommer/veins#237]
## I am submitting a...

  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support requests here (see the following note)

Is there a way I can change communication Range of VeinsInetCar ? I couldn't find anything on stackoverflow, I thought maybe there is not such feature in the VeinsInetCar module.

```
package vanettutorials.simulations.veins_inet;

import inet.physicallayer.ieee80211.packetlevel.Ieee80211ScalarRadioMedium;
import vanettutorials.veins_inet.VeinsInetCar;
import vanettutorials.veins_inet.VeinsInetManager;

network Scenario
{
    submodules:
        radioMedium: Ieee80211ScalarRadioMedium;
        manager: VeinsInetManager;
        node[0]: VeinsInetCar;
}
```

```
*.node[*].wlan[0].opMode = "p"
*.node[*].wlan[0].radio.bandName = "5.9 GHz"
*.node[*].wlan[0].radio.channelNumber = 3
*.node[*].wlan[0].radio.transmitter.power = 20mW
*.node[*].wlan[0].radio.bandwidth = 10 MHz
*.node[*].wlan[0].radio.communicationRange = 50m # absent
```

**Comment by sommer** [comment]
Veins_INET uses INET for radio communication, so all feature requests for radio models should be directed to the repo at https://github.com/inet-framework/inet
