### ISSUE TITLE
Changing deceleration value in real-time

### ISSUE THREAD

**Issue by ssooffiiaannee** [sommer/veins#238]
## I am submitting a...

  - [ ] bug report
  - [x] feature request
  - [x] support request => Please do not submit support requests here (see the following note)

This is highly likely to be a support request but I am not sure, and I cannot ask questions on SO since I did not reach the required privileges yet.

I am trying to modify the "decel" value of a vehicle in real-time, I put the following instruction in the "handlePositionUpdate" method: 
``` 
obility->getVehicleCommandInterfarce()->setParameter('decel', #number);
```

## What is the current behavior?
Nothing changes, debugging using the getDeccel() method just after setting it shows that the "decel" value does not change from the initial value.

## What is the expected behavior?
The goal is to change the deceleration in real-time to represent real scenarios. In reality, acceleration and deceleration depend, among other things, on the speed of the vehicle.

**Comment by sommer** [comment]
You opened the same issue in https://github.com/eclipse/sumo/issues/11545
