### ISSUE TITLE
Questions on power level, delay, and path loss.

### ISSUE THREAD

**Issue by ssooffiiaannee** [sommer/veins#239]
## I am submitting a...

  - [ ] bug report
  - [ ] feature request
  - [x] support request => Please do not submit support requests here (see the following note)

This is a support request,  I cannot ask questions on SO because I don't have the required privileges yet.

I would like to ask about the communication protocol used for the Veins example. In the omnet.ini file, you specified in a comment that the 11p specific parameters (I suppose you are referring to the 801.11p protocol) are the following : 
```
*.connectionManager.sendDirect = true
*.connectionManager.maxInterfDist = 2600m
*.connectionManager.drawMaxIntfDist = false

*.**.nic.mac1609_4.useServiceChannel = false

*.**.nic.mac1609_4.txPower = 20mW
*.**.nic.mac1609_4.bitrate = 6Mbps
*.**.nic.phy80211p.minPowerLevel = -110dBm

*.**.nic.phy80211p.useNoiseFloor = true
*.**.nic.phy80211p.noiseFloor = -98dBm

*.**.nic.phy80211p.decider = xmldoc("config.xml")
*.**.nic.phy80211p.analogueModels = xmldoc("config.xml")
*.**.nic.phy80211p.usePropagationDelay = true

*.**.nic.phy80211p.antenna = xmldoc("antenna.xml", "/root/Antenna[@id='monopole']")
*.node[*].nic.phy80211p.antennaOffsetY = 0 m
*.node[*].nic.phy80211p.antennaOffsetZ = 1.895 m
```
Are txPower, minPowerLevel, noiseFloor part of the 11p specifications? I think they are antenna-dependant and are not fixed as part of the standard. 

- Anyway, I am saying this because when I try to measure the communication range between vehicles, by using the default  "simplePathLossModel" with different alphas, two vehicles in a straight path, with no obstacles : 

alpha = 2            Communication range is between 585m and 590m
alpha = 3            Communication range is between 50m and 75m
I thought it was fishy because alpha is greater than 3 in urban areas and we get such a (relatively) low range with a = 3. Are these results confirmed by real scenarios?

- My next question is about transmission errors, I noticed that errors occur (message is lost) even when the received power is slightly higher than the minPowerLevel value ("packet has bit errors due to low power. Lost"). I checked the decided80211p.cc src file and couldn't sort things out, how does the decider work?

- This question is about latency, are latency values defined somewhere? I found that there is more than propagation delay, are any latencies introduced in other modules?

- My last question: can we somehow consider vehicles as obstacles? if one vehicle between two is disconnected for example. Can we consider the path loss due to the vehicle in the middle?

There are many questions, I'm not sure if I shall open different issues, looking forward to your comments :).

**Comment by sommer** [comment]
> I cannot ask questions on SO because I don't have the required privileges yet.

From what I understand, [asking a question on StackOverflow requires `1` reputation](https://stackoverflow.com/help/privileges), which is [the amount you have immediately after creating an account as a user](https://meta.stackexchange.com/questions/2621/why-does-reputation-start-at-1-and-have-a-lower-bound-of-1). So, from what I understand, everybody who successfully finished creating an account can immediately start asking questions.

What did I misunderstand here?

**Comment by ssooffiiaannee** [comment]
I already have an account, with 39 reputations. I need 50 reputations to comment, and I cannot ask questions until I improve my already existing questions they said. I improved them, and don't want to accept answers that do not answer my questions. But I will do it if necessary. Deleting questions will not solve the problem. I can create another account but this is not me.
