### ISSUE TITLE
"veins_launchd" may force SUMO terminated too early after  simulatiuon end

### ISSUE THREAD

**Issue by alanqq0624** [sommer/veins#240]
## I am submitting a...

  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support requests here (see the following note)

## What is the current behavior?

In current "veins_launchd" (Line 233-245), it will send "SIGKILL" and force OS to terminate the sumo program after 0.5 second 
 the "SIGTERM" signal.
But the SUMO program sometimes needs much more time to generate some sumo-related output completely.
If the sumo program ended too fast, the output file will miss lots of recording data which will affect the following data analysis process. 

For example, the running scenario is [LuST scenario](https://github.com/lcodeca/LuSTScenario) in my simulation.
And I add SSM devices to each vehicle to record a SSM output.
In my test, the sumo needs about 500 seconds to complete the generate after "SIGTERM".
But if I do not modify the waiting delay before the "SIGKILL", the SSM output file will be an incomplete file.

## What is the expected behavior?
Add more delay before the "SIGKILL".
Or make it keep waiting until the SUMO program terminate normally or some other signal involve.

**Comment by sommer** [comment]
The current version of SUMO's TraCI interface, unfortunately, only lends itself to a lot of guessing when it might become ready etc.; I agree that a longer timeout would be good, but how long is "long enough"? This is very specific to the simulation that the `launchd` is running for, so I believe the best option, as of right now, is to change the `launchd` locally.
