### ISSUE TITLE
OMNet ++ and veins how Can i fix this probleme 

### ISSUE THREAD

**Issue by Y-AMDIAZ** [sommer/veins#246]
/c/younes/omnetpp-5.6.2-src-windows/omnetpp-5.6.2$ C:\younes\veins-master\veins-master\sumo-launchd.py -vv -c 'C:\Program Files x86\Eclipse\Sumo\bin\sumo-gui.exe'
bash: C:younesveins-masterveins-mastersumo-launchd.py : commande introuvable

/c/younes/omnetpp-5.6.2-src-windows/omnetpp-5.6.2$ c\younes\veins-master\veins-master\sumo-launchd.py -vv -c 'c\Program Files x86\Eclipse\Sumo\bin\sumo-gui.exe'
bash: cyounesveins-masterveins-mastersumo-launchd.py : commande introuvable

/c/younes/omnetpp-5.6.2-src-windows/omnetpp-5.6.2$
<img width="440" alt="Capturejj" src="https://user-images.githubusercontent.com/129278941/231196507-77f0ea33-b452-4dab-9cd0-5f16a9fa0946.PNG">

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/
