### ISSUE TITLE
Message from RSU to RSU

### ISSUE THREAD

**Issue by ZeBarnabeMane** [sommer/veins#250]
Hi.
I'm trying to send a message from one RSU to another RSU. But the target RSU simply doesn't receive the message. Is this some limitation of the veins?
Thank you.

**Comment by sommer** [comment]
Thank you for your message, but this is most probably not the right place to have this discussion. We're using the Veins issue tracker only to track mistakes in Veins. While there is certainly a chance that you might have found a mistake, there is also a good chance that Veins is working as it should and, rather, your problem can be solved with some guidance. May I please point you to the Veins FAQ for further guidance and a list of preferred places for having discussions. You can find the FAQ at http://veins.car2x.org/documentation/faq/

**Comment by ZeBarnabeMane** [comment]
Ok, thanks Mr. Sommer.

**Answer here: **
https://stackoverflow.com/questions/77073101/how-to-send-message-from-rsu-to-rsu-veins-omnet-sumo
