### ISSUE TITLE
Some doubt about cca function

### ISSUE THREAD

**Issue by devilkuro** [sommer/veins#28]
Argument min(DimensionSet::timeFreqDomain());
	min.setTime(time);
	min.setArgValue(Dimension::frequency(), centerFrequency - 5e6);
	double minPower = MappingUtils::findMin(*resultMap, min, min, MappingUtils::cMaxNotFound());
	DBG_D11P << minPower << " > " << ccaThreshold << " = " << (bool)(minPower > ccaThreshold) << std::endl;

Why cca function only calculate the min frequency? 
Don't be

	Argument min(DimensionSet::timeFreqDomain());
	min.setTime(time);
	min.setArgValue(Dimension::frequency(), centerFrequency - 5e6);
	Argument max(DimensionSet::timeFreqDomain());
	max.setTime(time);
	max.setArgValue(Dimension::frequency(), centerFrequency + 5e6);
	double minPower = MappingUtils::findMax(*resultMap, min, max, MappingUtils::cMaxNotFound());

?

**Comment by sommer** [comment]
Frequency selective fading

**Comment by devilkuro** [comment]
Thanks for your reply.
I will try to learn some thing about Frequency selective fading first.
