### ISSUE TITLE
The pedestrian issue

### ISSUE THREAD

**Issue by devilkuro** [sommer/veins#29]
The default pedestrian type (seems a new function of sumo 0.29.0) 'DEFAULT_PEDTYPE' is regarded as a normal vehicle type.
And they will appear when the numVehicles is non-zero.
The related code is located at line 369 of TraCIScenarioManager.cc
see here: https://github.com/sommer/veins/blame/master/src/veins/modules/mobility/traci/TraCIScenarioManager.cc#L369
if (i->compare("DEFAULT_VEHTYPE")!=0)

change to 
if (i->compare("DEFAULT_VEHTYPE")!=0&&i->compare("DEFAULT_PEDTYPE")!=0) {

will fix this.

**Comment by chrisshen** [comment]
I met the same problem. 
My version is Veins 4.6
Going to modify the TraCIScenarioManager.cc, L421
`					
                                       if (i->compare("DEFAULT_VEHTYPE")!=0) {
						MYDEBUG << *i << std::endl;
						vehicleTypeIds.push_back(*i);
					}
`

**Comment by namnatulco** [comment]
I'm assuming this only happens for SUMO simulations where pedestrians are actually included (i.e., simulation results based on [the LuST scenario](https://github.com/lcodeca/LuSTScenario/wiki) are not going to be significantly different, can you confirm this?
