### ISSUE TITLE
archlinux + veins: shebang: configure fails 

### ISSUE THREAD

**Issue by sxleixer** [sommer/veins#32]
I'm using archlinux and I recently encountered a problem during configure phase.

The problem was related to the fact, that archlinux interprets the shebang `#!/usr/bin/env python` like `#!/usr/bin/env python3`. Thus the `print "..."` command fails.

A simple fix would be to change the shebang to `#!/usr/bin/env python2`. I hope that wouldn't break any other distributions.

**Comment by sommer** [comment]
Excellent idea. Tested on Ubuntu 16 and Windows and now implemented in fc0909fb104c4146afcf2938554574bb0e5ea4af

**Comment by sxleixer** [comment]
The current version of veins has the same problem again.

**Comment by sxleixer** [comment]
Sorry version 4.6 had this issue.
