### ISSUE TITLE
OMNeT++ 5.2.1 Debug Support

### ISSUE THREAD

**Issue by dbuse** [sommer/veins#59]
Since OMNeT++ 5.2 debug and release build can co-exist due to the prefix "_dbg" being attached to all debug-builds. So if Veins is built in debug mode, the resulting file is called _src/libveins_dbg.so_.
While release builds (the new default since 5.2) work fine, debug builds no longer work with the current helper scripts (run, debug, and memcheck) as they only look for src/libveins.so, not src/libveins_dbg.so.

Would it be possible to just adapt the helper scripts?

Note: The .so files are also built/copied directly into the src directory (in contrast to being symlinked as in previous versions).

**Comment by sommer** [comment]
Fixed in https://github.com/sommer/veins/commit/a85520ad

`./run` can now be run as `./run -d` to run the simulation in `opp_run_dbg`. At the same time, the `./debug` and `./memcheck` scripts have been integrated with the `./run` script as command line parameters `-t gdb` and `-t memcheck`
