### ISSUE TITLE
Simulation terminated with exit code: 139

### ISSUE THREAD

**Issue by kittu2910** [sommer/veins#81]
Hello,
I am getting the following error while running the ini file :
Simulation terminated with exit code: 139
Working directory: /home/pragya/veins-veins-4.6/examples/veins
Command line: opp_run -m -u Qtenv -n .:../../src/veins --image-path=../../images -l ../../src/veins omnetpp.ini

Environment variables:
PATH=/home/pragya/omnetpp-5.3/bin::/home/pragya/bin:/home/pragya/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH=/home/pragya/omnetpp-5.3/lib::/home/pragya/veins-veins-4.6/src:
OMNETPP_IMAGE_PATH=/home/pragya/omnetpp-5.3/images

How shall I overcome it?

**Comment by mightyCelu** [comment]
This is not a bug report, for these kinds of issues, try searching for similar issues at [stackoverflow](https://stackoverflow.com/questions/tagged/veins), and post your own question if you're unable to find any matching results. In particular, [this answer](https://stackoverflow.com/a/42695661/1733075) seems to apply to your issue.
