### ISSUE TITLE
Can't generate ned docs

### ISSUE THREAD

**Issue by shortwavedave** [sommer/veins#96]
I can't seem to generate the NED documentation from the IDE. This is the error I get:

![image](https://user-images.githubusercontent.com/22798574/48307041-cead6c00-e501-11e8-9602-46d6b26a4f6e.png)

**Comment by sommer** [comment]
According to an [OMNeT++ Users' Mailing List post by Levente Mészáros](https://groups.google.com/d/msg/omnetpp/zUITkbnpMAA/9Su6itdcCAAJ):
> It seems that the new MSG file format causes this internal error when generating NED documentation. If you are not using the new MSG file format, then the easiest workaround is to use an older OMNeT++ version to generate the NED documentation. The result will be the same as if you had used the new OMNeT++ release. **This bug will be fixed in the next OMNeT++ release**.
(highlight mine)

I also found that disabling the  **"Source Listings (NED, MSG)" option** (after clicking "Project > Generate NED Documentation..." but before clicking "OK") works around this issue.
